apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: servicio-api-mlops9-2
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/proj-mlops9-2/repo-mlops9-2/image-v5-servicio-mlops9-datapath:latest
          env:
          ports:
            - containerPort: 4001